# Use a special RP
resource_pack: httyd

# Use a different RP when combined with other configs
add_resource_pack: all

# Alternate resource packs can be accessed with /getrp <pack>
alternate_resource_packs:
  httyd:
    url: "https://rp.elmakers.com/Magic-httyd-1.17.zip"
